steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
  - name: 'gcr.io/cloud-builders/yarn:node-10.10.0'
    dir: "web"
    args: [ 'install' ]
  - name: 'gcr.io/cloud-builders/yarn:node-10.10.0'
    dir: "web"
    args: [ 'build' ]
  - name: 'gcr.io/stock-timing/firebase'
    args: [ 'deploy', '--only', 'hosting', '--token', '$_FIREBASE_TOKEN']
timeout: "900s"
