steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'cron.yaml']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/yarn:node-10.10.0'
    dir: 'web'
    args: ['install']
    waitFor: ['-']
    id: 'yarn install'
  - name: 'gcr.io/cloud-builders/yarn:node-10.10.0'
    dir: 'web'
    args: ['build']
    waitFor: ['yarn install']
  - name: 'tianhai/firebase'
    args:
      [
        'deploy',
        '--project',
        'stock-timing',
        '--only',
        'hosting',
        '--token',
        '$_FIREBASE_TOKEN',
      ]
timeout: '900s'
