steps:
  - id: preprocess-resources
    name: 'tianhai/envsubst:0.0.2'
    env: ["MAIL_API_KEY=$_MAIL_API_KEY"]
    args: ["app.yaml"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    waitFor: ['preprocess-resources']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'cron.yaml']
    waitFor: ['-']
  - name: 'node:10.10-alpine'
    dir: 'web'
    args: ['npm', 'install', '-g', 'yarn@berry']
    waitFor: ['-']
    id: 'install yarn'
  - name: 'node:10.10-alpine'
    dir: 'web'
    args: ['yarn']
    waitFor: ['install yarn']
    id: 'yarn install'
  - name: 'node:10.10-alpine'
    dir: 'web'
    args: ['yarn', 'build']
    waitFor: ['yarn install']
  - name: 'tianhai/firebase'
    args:
      [
        'deploy',
        '--project',
        'stock-timing',
        '--only',
        'hosting',
        '--token',
        '$_FIREBASE_TOKEN',
      ]
timeout: '900s'
